// Task Generator Hook - Phase 3: Background Generation System
// Based on RECURRING_REDESIGN_LOG.md specification

'use client'

import { useState, useCallback, useEffect } from 'react'
import { withErrorHandling } from '@/lib/utils/error-handler'
import { logger } from '@/lib/utils/logger'

interface UseTaskGeneratorResult {
  isGenerating: boolean
  lastError: string | null

  // Manual generation trigger
  generateMissingTasks: (forceToday?: boolean) => Promise<void>

  // Auto-generation on mount
  hasAutoGenerated: boolean
}

export function useTaskGenerator(autoGenerate: boolean = true): UseTaskGeneratorResult {
  const [isGenerating, setIsGenerating] = useState(false)
  const [lastError, setLastError] = useState<string | null>(null)
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false)

  // Manual generation trigger（API Route経由で実行）
  const generateMissingTasks = useCallback(async (forceToday?: boolean) => {
    if (isGenerating) return // Prevent concurrent generation

    await withErrorHandling(
      async () => {
        setIsGenerating(true)
        setLastError(null)

        logger.info('🔄 タスク生成を開始...')

        // API Routeを呼び出し（サーバー側で実行）
        const response = await fetch('/api/generate-tasks', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({ forceToday }),
        })

        if (!response.ok) {
          const error = await response.json()
          throw new Error(error.details || error.error || 'タスク生成に失敗しました')
        }

        logger.info('✅ タスク生成完了')

        // タスク一覧を自動リロードするためのイベントを発火
        logger.info('📢 Dispatching tasksUpdated event...')
        window.dispatchEvent(new CustomEvent('tasksUpdated'))
      },
      'useTaskGenerator.generateMissingTasks',
      setLastError
    )

    setIsGenerating(false)
  }, [isGenerating])

  // Auto-generation on component mount
  useEffect(() => {
    if (autoGenerate && !hasAutoGenerated && !isGenerating) {
      generateMissingTasks().then(() => {
        setHasAutoGenerated(true)
      })
    }
  }, [autoGenerate, hasAutoGenerated, isGenerating, generateMissingTasks])

  return {
    isGenerating,
    lastError,
    generateMissingTasks,
    hasAutoGenerated
  }
}